import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React from "react";
import {Header} from "@/widgets/Header/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  weight:['400', '600'],
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
    weight:['400', '600'],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
      template: '%s | Your Shop'
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
    <head>
        <title>Главная страница</title>
        <meta name="format-detection" content="telephone=no, date=no, email=no, address=no" />
    </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`} suppressHydrationWarning>
      <main>
          <Header />
          {children}
      </main>
      </body>
    </html>
  );
}
